[package]
name = "aoc-2022"
version = "0.1.0"
description = "Advent of Code 2022 in Rust"
authors = ["Floris Cornel <floris@cornel.email>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"
